### ISSUE TITLE
make failed during build-process

### ISSUE THREAD

**Issue by DB6KT** [KG5RKI/RT82Toolz#3]
Good afternoon,
I tryed to build the firmware image for my MD-2017 GPS and I received the followed error-massage: 

> "make" -C ../patches/FW_2017_GPS patched.img
make[2]: Verzeichnis „/home/db6kt/git-pakete/RT82Toolz/TyMD380tools/patches/FW_2017_GPS“ wird betreten
cd ../../firmware && "make" unwrapped/FW_2017_GPS.img
make[3]: Verzeichnis „/home/db6kt/git-pakete/RT82Toolz/TyMD380tools/firmware“ wird betreten
"make" -f Makefile_orig unwrapped/FW_2017_GPS.img
make[4]: Verzeichnis „/home/db6kt/git-pakete/RT82Toolz/TyMD380tools/firmware“ wird betreten
python ../md380_fw.py --unwrap bin/FW_2017_GPS.bin unwrapped/FW_2017_GPS.img
Traceback (most recent call last):
  File "../md380_fw.py", line 12, in <module>
    class MD380FW(object):
  File "../md380_fw.py", line 15, in MD380FW
    key = '00aa89891f4beccf424514540065eb66417d4c88495a210df2f5c8e638edbcb9fb357133010a7f9e3b2903b6493e42b83f9f90bdaa3a7146cecdfd183255894a5fc8839ce4069e0a9d0d2fa1356dd792eafd638590cbf02fd9595327d306b8f5b2ca886cd026913bf25b61becddbf21ac9fd8d8804f4e8f19a0292bc24e990e47ea3494dce529f58c17a5fb5186edb786408d56f0d9d9fb39930817e2be65b3c4aba8be5e472118993d2f12d1e0fd9d5438704e2b4ae5e9e5f4ce916f2e65f289f7919dc1d6f2ff8efcbe1cee8a73659efe0e28800106dda73bc922b81cfe6ce0447badb7e2f41ca5dcdf6417d1c382bef7d370af9a9148e5dea4466de8b3656018c358a119b8f2a6540f72ee6582874cbc4cb0fa7629be3a63cc76f130097e91eb15390dd9b613e908cad3c29414e5b0c1f664013244900d51ce2ed281853afe41cdc96ea18fe2e6519e01450c1f10939f5cf4544d5680d72f15f8823b9b1cfda36984341f8af236d50575e62bf5aa5daadcfc5425e3e34062304e90ecdf87189674e40e925bc452e97dcc16822d25877b12e6916a8149b181a9ab8f03b71bf7718c834ea856dbb325735e569d49f4a9968b4d8c79a316a303de89cd2eb64de2eafccc84d0209ae01f92b736dbc09a2c73a28ba5d1bdfcad6f6b83ebbc518f9369623a41983da4521e386137dc25a898a8f54b9e11564e393add046b3b1d7361533956f56ef26a91c7f0e6c9fced82669cffe7b5a6f09dceec8f95bc397e7bd55f0e9d10c3036017a348b27ddc8cda2ec62efa8d01116dd70b0fb25f15f91b77d34e974442d5276c169c4eb3f987f249bb1efe94be3d3109fcd9e4e47f11d4c16665bfd06cec2307b888261cc2737d5ff22c6e6d4cc879b0687aa7bcd35d3a3a7f0081758fbcd562ff88d318c5b3cdc9f1e3b4672b77ca62a47e6568a14fbe5b839b868449cbc106621ad02871dd862030e17b12e89f85a95731b878674dc39d2a93298d199d788a76baa7cc656518fb45822d10f2b44dece7511b6c93fbfc87ca8405007da66e37a3e4b4850ecf08a3966244b1d85a85b5db3908a5c5becba3e9ea838ef48b14c6702590e2dc9fd7c1a9ee5ca607f6bf9cb9760ab46b2ab36a0f333f790c900e9f71f9d7566d3c08ce06a2cf4e102d7df9e8748c28f2a44642b0fa936f3469ae2b1fddc2602f480e31231c371a7f4323661ed127740adfe6d665bd29c1ea8c8601e04e1c9091387a8385a70eaba3fc525993084715f222379d93d76d21bd5d28bc49d730584171b04db4ffc0723c9d8d5d0b86759f770f9af0d1e5c7ff2b7008a2d2e59827aea851f82772f6fe97cb36e8ded82d60d81c93889674d4ca9359986e1215ce9f3730d20b53ad0cb143e9d1759379f91ab3cda3cd57e11e04a36e7a666dc44e2f79afa30fc00a9c2adf9e0f8bbfe8431d88976e2'.decode('hex')
AttributeError: 'str' object has no attribute 'decode'
make[4]: *** [Makefile_orig:47: unwrapped/FW_2017_GPS.img] Fehler 1
make[4]: Verzeichnis „/home/db6kt/git-pakete/RT82Toolz/TyMD380tools/firmware“ wird verlassen
make[3]: *** [Makefile:33: unwrapped/FW_2017_GPS.img] Fehler 2
make[3]: Verzeichnis „/home/db6kt/git-pakete/RT82Toolz/TyMD380tools/firmware“ wird verlassen
make[2]: *** [Makefile:7: unwrapped.img] Fehler 2
make[2]: Verzeichnis „/home/db6kt/git-pakete/RT82Toolz/TyMD380tools/patches/FW_2017_GPS“ wird verlassen
make[1]: *** [Makefile:115: base.img] Fehler 2
make[1]: Verzeichnis „/home/db6kt/git-pakete/RT82Toolz/TyMD380tools/applet“ wird verlassen
make: *** [Makefile:40: image_2017_GPS] Fehler 2
<
I can´t found any solution and can´t fix the problem to get an running firmware-file. What´s wrong with me or my system ;-)
Tanks in advance
73 de Thomas, DB6KT

**Comment by DB6KT** [comment]
Ok - fix that issue - solution is to sell my MD-2017 and activate my old MD380!
Thanks !
73 de Thomas
